# Generated by Django 5.2.6 on 2025-09-24 14:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('alternate_names', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, null=True)),
                ('occupations', models.JSONField(blank=True, null=True)),
                ('years_active', models.CharField(blank=True, max_length=50, null=True)),
                ('agent', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_or_spouse', models.CharField(blank=True, max_length=255, null=True)),
                ('dramabeans_url', models.URLField(blank=True, null=True, unique=True)),
                ('wikipedia_url', models.URLField(blank=True, null=True, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kdrama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('writers', models.JSONField(blank=True, null=True)),
                ('directors', models.JSONField(blank=True, null=True)),
                ('dramabeans_url', models.URLField(blank=True, null=True, unique=True)),
                ('wikipedia_url', models.URLField(blank=True, null=True, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('alternate_titles', models.JSONField(blank=True, null=True)),
                ('genre', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('network', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.CharField(blank=True, null=True)),
                ('running_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Krole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdramavibe_scrapper.kactor')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdramavibe_scrapper.kdrama')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kactor',
            name='dramas',
            field=models.ManyToManyField(through='kdramavibe_scrapper.Krole', to='kdramavibe_scrapper.kdrama'),
        ),
    ]
