# Generated by Django 5.2.6 on 2025-10-16 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kactor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("alternate_names", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("birthplace", models.CharField(blank=True, max_length=255, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("occupations", models.JSONField(blank=True, null=True)),
                ("children", models.JSONField(blank=True, null=True)),
                (
                    "years_active",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("agents", models.JSONField(blank=True, null=True)),
                ("height", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "partner_or_spouse",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("wikipedia_url", models.URLField(blank=True, null=True, unique=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Kdrama",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("start_year", models.CharField(blank=True, max_length=10, null=True)),
                ("end_year", models.CharField(blank=True, max_length=10, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("total_rating", models.FloatField(blank=True, null=True)),
                ("plot", models.TextField(blank=True, null=True)),
                ("writers", models.JSONField(blank=True, null=True)),
                ("languages", models.JSONField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("directors", models.JSONField(blank=True, null=True)),
                ("wikipedia_url", models.URLField(unique=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("alternate_titles", models.JSONField(blank=True, null=True)),
                ("genres", models.JSONField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("episodes", models.JSONField(blank=True, null=True)),
                ("seasons", models.CharField(blank=True, max_length=10, null=True)),
                ("networks", models.JSONField(blank=True, null=True)),
                (
                    "running_time",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Krole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role_name", models.TextField(blank=True, null=True)),
                (
                    "kactor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kactors_roles",
                        to="kdramavibe_scrapper.kactor",
                    ),
                ),
                (
                    "kdrama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kdramas_roles",
                        to="kdramavibe_scrapper.kdrama",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="kactor",
            name="kdramas",
            field=models.ManyToManyField(
                through="kdramavibe_scrapper.Krole", to="kdramavibe_scrapper.kdrama"
            ),
        ),
    ]
