# Generated by Django 5.2.6 on 2025-10-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kactor",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="kdrama",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
