# Generated by Django 5.2.6 on 2025-09-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdramavibe_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kactor',
            old_name='dramas',
            new_name='kdramas',
        ),
        migrations.RenameField(
            model_name='krole',
            old_name='actor',
            new_name='kactor',
        ),
        migrations.RenameField(
            model_name='krole',
            old_name='drama',
            new_name='kdrama',
        ),
        migrations.AddField(
            model_name='kdrama',
            name='total_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
