# Generated by Django 5.2.6 on 2025-09-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdramavibe_scrapper', '0002_rename_dramas_kactor_kdramas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krole',
            name='role_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
