# Generated by Django 5.2.6 on 2025-10-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0002_alter_kactor_image_url_alter_kdrama_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kdrama",
            name="running_time",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
