# Generated by Django 5.2.6 on 2025-10-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0003_alter_kdrama_running_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kactor",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="kdrama",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
