# Generated by Django 5.2.6 on 2025-09-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdramavibe_scrapper', '0003_alter_krole_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kactor',
            name='birthday',
            field=models.CharField(blank=True, null=True),
        ),
    ]
