# Generated by Django 5.2.6 on 2025-10-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0004_alter_kactor_slug_alter_kdrama_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kactor",
            name="years_active",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
