# Generated by Django 5.2.6 on 2025-09-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdramavibe_scrapper', '0004_alter_kactor_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='kactor',
            name='birthplace',
            field=models.CharField(blank=True, null=True),
        ),
    ]
