# Generated by Django 5.2.6 on 2025-09-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdramavibe_scrapper', '0005_kactor_birthplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kactor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='kdrama',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
