# Generated by Django 5.2.6 on 2025-11-03 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0005_alter_kactor_years_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="DramabeansKdramas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("year", models.CharField(blank=True, max_length=10, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("total_rating", models.FloatField(blank=True, null=True)),
                ("no_of_votes", models.FloatField(blank=True, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="kdrama",
            name="no_of_votes",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
