# Generated by Django 5.2.6 on 2025-09-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdramavibe_scrapper', '0006_alter_kactor_name_alter_kdrama_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krole',
            name='kactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kroles', to='kdramavibe_scrapper.kactor'),
        ),
        migrations.AlterField(
            model_name='krole',
            name='kdrama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kroles', to='kdramavibe_scrapper.kdrama'),
        ),
    ]
