# Generated by Django 5.2.6 on 2025-11-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0006_dramabeanskdramas_kdrama_no_of_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="dramabeanskdramas",
            name="dramabeans_url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="kactor",
            name="dramabeans_url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
