# Generated by Django 5.2.6 on 2025-09-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdramavibe_scrapper', '0007_alter_krole_kactor_alter_krole_kdrama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krole',
            name='kactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kactors_roles', to='kdramavibe_scrapper.kactor'),
        ),
        migrations.AlterField(
            model_name='krole',
            name='kdrama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kdramas_roles', to='kdramavibe_scrapper.kdrama'),
        ),
    ]
