# Generated by Django 5.2.6 on 2025-11-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0007_dramabeanskdramas_dramabeans_url_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DramabeansKdramas", new_name="DramabeansKdrama",
        ),
    ]
