# Generated by Django 5.2.6 on 2025-11-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0008_rename_dramabeanskdramas_dramabeanskdrama"),
    ]

    operations = [
        migrations.RemoveField(model_name="dramabeanskdrama", name="total_rating",),
        migrations.RemoveField(model_name="kdrama", name="total_rating",),
    ]
