# Generated by Django 5.2.6 on 2025-10-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdramavibe_scrapper', '0008_alter_krole_kactor_alter_krole_kdrama'),
    ]

    operations = [
        migrations.AddField(
            model_name='kactor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
    ]
