# Generated by Django 5.2.6 on 2025-10-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdramavibe_scrapper', '0009_kactor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdrama',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
