# Generated by Django 5.2.6 on 2025-11-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0009_remove_dramabeanskdrama_total_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kdrama",
            name="dramabeans_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
