# Generated by Django 5.2.6 on 2025-11-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0010_kdrama_dramabeans_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="kdrama", name="dramabeans_title",),
        migrations.RemoveField(model_name="kdrama", name="no_of_votes",),
        migrations.RemoveField(model_name="kdrama", name="rating",),
    ]
