# Generated by Django 5.2.6 on 2025-10-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdramavibe_scrapper', '0010_kdrama_plot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kactor',
            old_name='dramabeans_url',
            new_name='asianwiki_url',
        ),
        migrations.RenameField(
            model_name='kactor',
            old_name='bio',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='kactor',
            old_name='birthday',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='kactor',
            old_name='years_active',
            new_name='blood_type',
        ),
        migrations.RenameField(
            model_name='kactor',
            old_name='agent',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='kactor',
            old_name='partner_or_spouse',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='kdrama',
            old_name='dramabeans_url',
            new_name='asianwiki_url',
        ),
        migrations.RenameField(
            model_name='kdrama',
            old_name='rating',
            new_name='percentage_rating',
        ),
        migrations.RenameField(
            model_name='kdrama',
            old_name='total_rating',
            new_name='total_votes',
        ),
        migrations.RemoveField(
            model_name='kactor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='kactor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kactor',
            name='education',
        ),
        migrations.RemoveField(
            model_name='kactor',
            name='occupations',
        ),
        migrations.RemoveField(
            model_name='kactor',
            name='wikipedia_url',
        ),
        migrations.RemoveField(
            model_name='kdrama',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kdrama',
            name='wikipedia_url',
        ),
        migrations.AddField(
            model_name='kdrama',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kdrama',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
