# Generated by Django 5.2.6 on 2025-11-03 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0011_remove_kdrama_dramabeans_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dramabeanskdrama",
            name="kdrama",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dramabeans_details",
                to="kdramavibe_scrapper.kdrama",
            ),
        ),
    ]
