# Generated by Django 5.2.6 on 2025-10-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdramavibe_scrapper', '0011_rename_dramabeans_url_kactor_asianwiki_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kdrama',
            name='year',
        ),
    ]
