# Generated by Django 5.2.6 on 2025-11-03 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0012_dramabeanskdrama_kdrama"),
    ]

    operations = [
        migrations.CreateModel(
            name="DramabeansKactor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("no_of_votes", models.FloatField(blank=True, null=True)),
                ("dramabeans_url", models.URLField(blank=True, null=True, unique=True)),
                (
                    "kactor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dramabeans_details",
                        to="kdramavibe_scrapper.kactor",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
