# Generated by Django 5.2.6 on 2025-10-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdramavibe_scrapper', '0012_remove_kdrama_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kactor',
            old_name='family',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='kactor',
            old_name='biography',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='kactor',
            old_name='birthdate',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='kactor',
            old_name='asianwiki_url',
            new_name='dramabeans_url',
        ),
        migrations.RenameField(
            model_name='kactor',
            old_name='weight',
            new_name='partner_or_spouse',
        ),
        migrations.RenameField(
            model_name='kactor',
            old_name='blood_type',
            new_name='years_active',
        ),
        migrations.RenameField(
            model_name='kdrama',
            old_name='asianwiki_url',
            new_name='dramabeans_url',
        ),
        migrations.RenameField(
            model_name='kdrama',
            old_name='percentage_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='kdrama',
            old_name='total_votes',
            new_name='total_rating',
        ),
        migrations.AddField(
            model_name='kactor',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kactor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kactor',
            name='education',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kactor',
            name='occupations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kactor',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kdrama',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kdrama',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kdrama',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
