# Generated by Django 5.2.6 on 2025-10-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0013_rename_family_kactor_agent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kdrama", old_name="genre", new_name="genres",
        ),
        migrations.RemoveField(model_name="kdrama", name="country",),
        migrations.RemoveField(model_name="kdrama", name="language",),
        migrations.RemoveField(model_name="kdrama", name="network",),
        migrations.AddField(
            model_name="kdrama",
            name="networks",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kdrama",
            name="wikipedia_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
