# Generated by Django 5.2.6 on 2025-11-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0013_dramabeanskactor"),
    ]

    operations = [
        migrations.AddField(
            model_name="dramabeanskactor",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
