# Generated by Django 5.2.6 on 2025-10-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kdramavibe_scrapper",
            "0014_rename_genre_kdrama_genres_remove_kdrama_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="kdrama",
            name="episodes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
