# Generated by Django 5.2.6 on 2025-11-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0014_dramabeanskactor_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="dramabeanskactor",
            name="birthday",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dramabeanskactor",
            name="birthplace",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
