# Generated by Django 5.2.6 on 2025-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0015_alter_kdrama_episodes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kdrama", old_name="release_date", new_name="country",
        ),
        migrations.AddField(
            model_name="kdrama",
            name="end_year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="kdrama",
            name="languages",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kdrama",
            name="release_dates",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
