# Generated by Django 5.2.6 on 2025-11-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0015_dramabeanskactor_birthday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dramabeanskactor",
            name="birthday",
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
