# Generated by Django 5.2.6 on 2025-10-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "kdramavibe_scrapper",
            "0016_rename_release_date_kdrama_country_kdrama_end_year_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="kdrama", name="description",),
    ]
