# Generated by Django 5.2.6 on 2025-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0017_remove_kdrama_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="kdrama", name="dramabeans_url",),
        migrations.RemoveField(model_name="kdrama", name="wikipedia_image_url",),
        migrations.AddField(
            model_name="kdrama",
            name="seasons",
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
