# Generated by Django 5.2.6 on 2025-10-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0018_remove_kdrama_dramabeans_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kdrama",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kdrama",
            name="seasons",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kdrama",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
