# Generated by Django 5.2.6 on 2025-10-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "kdramavibe_scrapper",
            "0019_alter_kdrama_end_year_alter_kdrama_seasons_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="kdrama", name="release_dates",),
    ]
