# Generated by Django 5.2.6 on 2025-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0020_remove_kdrama_release_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kdrama",
            name="end_year",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="kdrama",
            name="seasons",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="kdrama",
            name="year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
