# Generated by Django 5.2.6 on 2025-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kdramavibe_scrapper",
            "0021_alter_kdrama_end_year_alter_kdrama_seasons_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="kdrama",
            name="end_year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
