# Generated by Django 5.2.6 on 2025-10-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0022_alter_kdrama_end_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kdrama", old_name="year", new_name="start_year",
        ),
    ]
