# Generated by Django 5.2.6 on 2025-10-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0023_rename_year_kdrama_start_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kdrama",
            name="wikipedia_url",
            field=models.URLField(default="none", unique=True),
            preserve_default=False,
        ),
    ]
