# Generated by Django 5.2.6 on 2025-10-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0024_alter_kdrama_wikipedia_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="krole",
            name="role_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
