# Generated by Django 5.2.6 on 2025-10-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0025_alter_krole_role_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kactor", old_name="birthplace", new_name="birth_name",
        ),
        migrations.RemoveField(model_name="kactor", name="bio",),
        migrations.RemoveField(model_name="kactor", name="gender",),
        migrations.AddField(
            model_name="kactor",
            name="birth_place",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kactor",
            name="children",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
