# Generated by Django 5.2.6 on 2025-10-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0026_rename_birthplace_kactor_birth_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="kactor", name="education",),
    ]
