# Generated by Django 5.2.6 on 2025-10-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0027_remove_kactor_education"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kactor", old_name="birth_name", new_name="birthplace",
        ),
        migrations.RemoveField(model_name="kactor", name="birth_place",),
    ]
