# Generated by Django 5.2.6 on 2025-10-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0028_rename_birth_name_kactor_birthplace_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="kactor", name="dramabeans_url",),
    ]
