# Generated by Django 5.2.6 on 2025-10-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0029_remove_kactor_dramabeans_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="kactor", name="children",),
    ]
