# Generated by Django 5.2.6 on 2025-10-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0030_remove_kactor_children"),
    ]

    operations = [
        migrations.AddField(
            model_name="kactor",
            name="children",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
