# Generated by Django 5.2.6 on 2025-10-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdramavibe_scrapper", "0031_kactor_children"),
    ]

    operations = [
        migrations.AddField(
            model_name="kactor",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=6,
                null=True,
            ),
        ),
    ]
