export const WOMAN_PLACEHOLDER = "/images/woman.png";
export const MAN_PALCEHOLDER = "/images/man.png";
export const PLACEHOLDER = "/images/placeholder.png";

export const GENDER_OPTIONS: { name: string; value: string }[] = [
  { name: "All", value: "" },
  { name: "Woman", value: "Woman" },
  { name: "Man", value: 'Man' }
]
export const NAV_LINKS: { name: string, href: string }[] = [
  {
    name: "K-dramas",
    href: "/"
  },
  {
    name: "K-actors",
    href: "/k-actors"
  },
  {
    name: "About",
    href: "/about"
  }
];

export const GENRES_OPTIONS: string[] = [
  "Action",
  "Action-adventure",
  "Action comedy",
  "Action drama",
  "Action thriller",
  "Adventure",
  "Alternate History",
  "Anthology",
  "Anthology series",
  "Apocalyptic",
  "Autobiography",
  "Biopic",
  "Black comedy",
  "Body snatcher",
  "Body swap",
  "Boys' Love",
  "Business",
  "Children's drama",
  "Children's television series",
  "Comedy",
  "Comedy drama",
  "Comedy-drama",
  "Coming of age",
  "Coming-of-age",
  "Cooking",
  "Corporate",
  "Courtroom drama",
  "Crime",
  "Crime action",
  "Crime comedy",
  "Crime drama",
  "Crime thriller",
  "Dark comedy",
  "Dark fantasy",
  "Detective",
  "Detective fiction",
  "Disaster",
  "Docudrama",
  "Domestic",
  "Drama",
  "Drama thriller",
  "Dramedy",
  "Dystopian",
  "Dystopian fiction",
  "Epic",
  "Erotica",
  "Erotica Drama",
  "Espionage",
  "Fantasy",
  "Fantasy action",
  "Fantasy drama",
  "Fantasy romance",
  "Fantasy television",
  "Fiction",
  "Finance",
  "Fitness",
  "Folklore",
  "Food",
  "Friendship",
  "Gambling",
  "Gangster",
  "Hardboiled",
  "Heist",
  "Historical",
  "Historical drama",
  "Historical fiction",
  "Historical fusion",
  "Historical Medicine",
  "Historical period",
  "Historical period drama",
  "Historical romance",
  "History",
  "Horror",
  "Human",
  "Humanism",
  "Korean drama",
  "Law",
  "Legal",
  "Legal drama",
  "Legal thriller",
  "Life",
  "Medical",
  "Medical drama",
  "Medical thriller",
  "Melodrama",
  "Melodrama, romance, family",
  "Military",
  "Military drama",
  "Military sci-fi",
  "Miniseries",
  "Mockumentary",
  "Music",
  "Musical",
  "Musical drama",
  "Mystery",
  "Noir",
  "Occult",
  "Occult detective fiction",
  "Office",
  "Office comedy",
  "Omnibus",
  "Period",
  "Period drama",
  "Picaresque",
  "Political",
  "Political drama",
  "Political thriller",
  "Police procedural",
  "Politics",
  "Procedural",
  "Procedural drama",
  "Psychological",
  "Psychological drama",
  "Psychological thriller",
  "Reality",
  "Reincarnation",
  "Revenge",
  "Revenge drama",
  "Rom-com",
  "Romance",
  "Romance comedy",
  "Romance drama",
  "Romance, Comedy",
  "Romance, Drama",
  "Romance, Drama, Fantasy",
  "Romance comedy",
  "Romantic",
  "Romantic comedy",
  "Romantic fantasy",
  "Romantic drama",
  "Romantic thriller",
  "Romantic-comedy",
  "Sageuk",
  "Satire",
  "Satirical drama",
  "School",
  "School drama",
  "School Life",
  "Sci-fi",
  "Science fantasy",
  "Science fiction",
  "Serial",
  "Situation comedy",
  "Slice of life",
  "Slice of life story",
  "Slice-of-life",
  "Snob Drama",
  "Soap opera",
  "Social satire",
  "Sport",
  "Sports",
  "Sports drama",
  "Spy",
  "Superhero",
  "Superhero fiction",
  "Supernatural",
  "Supernatural thriller",
  "Survival",
  "Suspense",
  "Suspense thriller",
  "Teen",
  "Teen comedy",
  "Teen drama",
  "Teen romance",
  "Thriller",
  "Time slip",
  "Time travel",
  "Tokusatsu",
  "Tragedy",
  "Tragicomedy",
  "Unreliable source?",
  "Vampire",
  "Variety show",
  "Vigilante",
  "War",
  "War drama",
  "Web series",
  "Web television",
  "Workplace",
  "Workplace comedy",
  "Workplace drama",
  "Youth",
  "Youth Drama",
  "Zombie apocalypse",
  "Zombie comedy"
];

